  name: Build and deploy Node.js app to Azure Web App - robin-webapp
  
  on:
    push:
      branches:
        - main
    workflow_dispatch:
  
  jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
        - uses: actions/checkout@v4
  
        - name: Set up Node.js version
          uses: actions/setup-node@v3
          with:
            node-version: '18.x'
            cache: 'yarn' # Enable Yarn caching if Yarn is used
  
        - name: Install Vite globally
          run: npm install -g vite
  
        - name: Install dependencies with Yarn
          run: yarn install
  
        - name: Build the project with Vite
          run: yarn build
  
        - name: Zip the build directory for deployment
          run: zip -r release.zip ./dist/* # Replace `dist` with your actual build output directory
  
        - name: Upload artifact for deployment job
          uses: actions/upload-artifact@v3
          with:
            name: node-app
            path: release.zip
  
    deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'Production'
      permissions:
        id-token: write # This is required for requesting the JWT
  
      steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v3
          with:
            name: node-app
  
        - name: Unzip artifact for deployment
          run: unzip release.zip
  
        - name: Login to Azure
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B28FFCC6CD6A4166860F6606D500286E }}
            tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_03E6531CD1824007AEF42690D74D1AF8 }}
            subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DBC7758D656E4C0BA59927BE0987CA71 }}
  
        - name: Deploy to Azure Web App
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'robin-webapp'
            package: release.zip
